### ISSUE TITLE
Add support for building Janus plugin

### ISSUE THREAD

**Issue by mtlynch** [tiny-pilot/ansible-role-ustreamer#49]
Versions of uStreamer after 4.x contain a plugin for Janus that requires separate compilation:

https://github.com/tiny-pilot/ustreamer/tree/421f4a1f2e34850554fe9f83610a60a833a1ff98/janus

We need to add an option in the role for compiling this plugin.

**Comment by jdeanwallace** [comment]
I'm unable to build the uStreamer Janus plugin without having Janus itself built/configured:

```bash
root@raspberrypi:/opt/ustreamer# make WITH_JANUS=1
...
make[2]: Entering directory '/opt/ustreamer/janus'
-- CC src/base64.c
-- CC src/frame.c
-- CC src/plugin.c
src/plugin.c:37:10: fatal error: janus/config.h: No such file or directory
 #include <janus/config.h>
```

I assume we need to configure Janus ([like we do in the proof-of-concept here](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/cffa95cc59864343f1c5d658a095a32fb2e7da01/janus_ustreamer_docker/Dockerfile#L62)) in order for the [Janus plugin to include the `janus/config.h` file](https://github.com/tiny-pilot/ustreamer/blob/421f4a1f2e34850554fe9f83610a60a833a1ff98/janus/src/plugin.c#L37-L38).

I think we need to move this task down our [H264 todo list](https://github.com/tiny-pilot/tinypilot/issues/875#issue-1090148533) to something like:
- [x] ...
- [ ] ansible-role-tinypilot: [Generalize H264 Docker image to work with Hobbyist or Voyager](https://github.com/tiny-pilot/ansible-role-tinypilot/issues/178)
- [ ] ansible-role-tinypilot: [Remove uStreamer from proof-of-concept Docker image](https://github.com/tiny-pilot/ansible-role-tinypilot/issues/179)
- [ ] **ansible-role-ustreamer: [Add support for building Janus plugin](https://github.com/tiny-pilot/ansible-role-ustreamer/issues/49)**
- [ ] ...

That way, we'll have Janus running in it's own docker container and be able to expose the [source files](https://github.com/tiny-pilot/ustreamer/blob/421f4a1f2e34850554fe9f83610a60a833a1ff98/janus/src/plugin.c#L37-L38) needed to build the Janus plugin. Do you think would be possible?

**Comment by mtlynch** [comment]
Oh, that's a pain.

>At which point, we'll have Janus running in it's own docker container and be able to expose the [source files](https://github.com/tiny-pilot/ustreamer/blob/421f4a1f2e34850554fe9f83610a60a833a1ff98/janus/src/plugin.c#L37-L38) needed to build the Janus plugin. Do you think would be possible?

That's pretty hard to work with, as it creates a circular dependency between the Docker container and uStreamer on the host. Because I think the sequence would have to be:

1. Start Janus container, sharing the `/usr/include/janus` directory with the host system
2. Compile uStreamer and the Janus plugin
3. Copy the uStreamer Janus plugin into the Janus container
4. Restart Janus to load the plugin (?)

I think what we should do instead:

1. Proceed with fixing this bug anyway, even if we can't fully test it at this point (i.e. add a var in `defaults/main.yml` that controls whether we compile with Janus and then adjust the `make` command so that it adds the appropriate `WITH_JANUS=1` if the var is set.
1. Instead of totally stripping uStreamer out of the proof of concept Docker image, we'll just strip out [the part where we launch it as a service](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/48463dc5ef35bbdd373bb6c4a55600ceacd1a765/janus_ustreamer_docker/start.sh#L1). We'll still [compile the plugin](https://github.com/tiny-pilot/ansible-role-tinypilot/blob/48463dc5ef35bbdd373bb6c4a55600ceacd1a765/janus_ustreamer_docker/Dockerfile#L70L73) in the Docker container, and that's how we'll create the plugin during testing.

**Comment by mtlynch** [comment]
>What if we share the container's entire /opt/janus/ directory with the host system? That way, we can place our compiled uStreamer plugin into /opt/janus/lib/janus/plugins/ and restart the container as needed.

Eh, still pretty ugly. You generally don't want a compilation step on the host to depend on a particular Docker container being up and running.

It's not so ugly to build uStreamer in both places. The container is what needs the Janus plugin, so it makes sense to do the compilation there. We just end up with an extra uStreamer server binary we don't need in the container, but that's fine for now.
